# required configuration options
name: Fork-Fusion
version: 2024.10.1
slug: ha_fusion
description: A modern, easy-to-use and performant custom Home Assistant dashboard
arch:
  - aarch64
  - amd64
  - armv7

# disable the docker default system init
init: false

# homepage of the add-on
url: https://github.com/zero5549/addon-ha-fusion

# icon for the menu panel integration
panel_icon: mdi:atom

# allow non-administration users
panel_admin: false

# security profile
apparmor: true

# ingress feature for the add-on
ingress: true
ingress_stream: true

# enable api to get host port
hassio_api: true

# port to expose, null defaults to disabled
ports:
  8099/tcp: null

# docker hub
image: matt8707/addon-ha-fusion-{arch}
